source 'https://rubygems.org'


gem 'actionpack'
gem 'actionview'
gem 'bundler'
gem 'railties'
gem 'jquery-rails'
gem 'unicorn'
gem 'rspec-rails'
gem 'noughts_and_crosses', :path => '../core'
gem 'noughts_and_crosses_ui_core', :path => '../ui_core'
